name: publish
on: 
  workflow_dispatch:
  push:
    tags:

jobs:
  release-service-broker-docker-image: # build and push docker image (this includes a gradle build running in docker)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lowercase repository name # docker needs a lowercase name, see https://github.community/t/additional-function-s-lowercase-uppercase/140632
      run: |
        echo "REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
    - name: Create docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/fnts-public/osb_runner_image
        tags: type=ref,event=tag
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        repository: ${{ env.REPO }}
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ steps.meta.outputs.tags }}